/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-3",
    "aws_cognito_identity_pool_id": "eu-west-3:5d17b5f4-513f-4cfd-bb5a-b84003a1fe74",
    "aws_cognito_region": "eu-west-3",
    "aws_user_pools_id": "eu-west-3_QBGEWlnF5",
    "aws_user_pools_web_client_id": "7p2lpmhl97ilnm1j4joe1o7vpp",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://j6f5jfobijgcligr4nunpprfqa.appsync-api.eu-west-3.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-3",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-lplrckeatbbedjj3bd5acvgnta",
    "aws_user_files_s3_bucket": "s3dropboxcbb1c-dev",
    "aws_user_files_s3_bucket_region": "eu-west-3"
};


export default awsmobile;
